//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recruitment.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Recruitment.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Апликација.
        /// </summary>
        public static string _Application {
            get {
                return ResourceManager.GetString("_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Избриши.
        /// </summary>
        public static string _Delete {
            get {
                return ResourceManager.GetString("_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детали.
        /// </summary>
        public static string _Details {
            get {
                return ResourceManager.GetString("_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Промени.
        /// </summary>
        public static string _Edit {
            get {
                return ResourceManager.GetString("_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здраво.
        /// </summary>
        public static string _Hello {
            get {
                return ResourceManager.GetString("_Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Почетна.
        /// </summary>
        public static string _HomePage {
            get {
                return ResourceManager.GetString("_HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Најави се.
        /// </summary>
        public static string _LogIn {
            get {
                return ResourceManager.GetString("_LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отворени работни места.
        /// </summary>
        public static string _OpenJobs {
            get {
                return ResourceManager.GetString("_OpenJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прашања и одговори.
        /// </summary>
        public static string _QnA {
            get {
                return ResourceManager.GetString("_QnA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прашалник.
        /// </summary>
        public static string _Questionare {
            get {
                return ResourceManager.GetString("_Questionare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрирај се.
        /// </summary>
        public static string _Register {
            get {
                return ResourceManager.GetString("_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профили.
        /// </summary>
        public static string _UserProfiles {
            get {
                return ResourceManager.GetString("_UserProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Корисници.
        /// </summary>
        public static string _Users {
            get {
                return ResourceManager.GetString("_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Работни места.
        /// </summary>
        public static string _WorkPosition {
            get {
                return ResourceManager.GetString("_WorkPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Одговори.
        /// </summary>
        public static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Одговори опис.
        /// </summary>
        public static string Answer_Desrciption {
            get {
                return ResourceManager.GetString("Answer_Desrciption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прифатен?.
        /// </summary>
        public static string Aplication_Accepted {
            get {
                return ResourceManager.GetString("Aplication_Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адреса на живеење.
        /// </summary>
        public static string Aplication_Address {
            get {
                return ResourceManager.GetString("Aplication_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Град.
        /// </summary>
        public static string Aplication_City {
            get {
                return ResourceManager.GetString("Aplication_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кратка биографија (CV).
        /// </summary>
        public static string Aplication_CV {
            get {
                return ResourceManager.GetString("Aplication_CV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Датум на раѓање.
        /// </summary>
        public static string Aplication_DateOfBirth {
            get {
                return ResourceManager.GetString("Aplication_DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Е-маил.
        /// </summary>
        public static string Aplication_Email {
            get {
                return ResourceManager.GetString("Aplication_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име.
        /// </summary>
        public static string Aplication_FirstName {
            get {
                return ResourceManager.GetString("Aplication_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Презиме.
        /// </summary>
        public static string Aplication_LastName {
            get {
                return ResourceManager.GetString("Aplication_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        public static string Aplication_Phone {
            get {
                return ResourceManager.GetString("Aplication_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Работно место.
        /// </summary>
        public static string Aplication_WorkPosition_id {
            get {
                return ResourceManager.GetString("Aplication_WorkPosition_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аплицирај.
        /// </summary>
        public static string Apply_ForJob {
            get {
                return ResourceManager.GetString("Apply_ForJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        public static string Button_Back {
            get {
                return ResourceManager.GetString("Button_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запиши.
        /// </summary>
        public static string Button_Create {
            get {
                return ResourceManager.GetString("Button_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нов запис.
        /// </summary>
        public static string Button_CreateNew {
            get {
                return ResourceManager.GetString("Button_CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Избриши.
        /// </summary>
        public static string Button_Delete {
            get {
                return ResourceManager.GetString("Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детали.
        /// </summary>
        public static string Button_Details {
            get {
                return ResourceManager.GetString("Button_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Промени.
        /// </summary>
        public static string Button_Edit {
            get {
                return ResourceManager.GetString("Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повеќе.
        /// </summary>
        public static string Button_LearnMore {
            get {
                return ResourceManager.GetString("Button_LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Најави се.
        /// </summary>
        public static string Button_LogIn {
            get {
                return ResourceManager.GetString("Button_LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрирај се.
        /// </summary>
        public static string Button_Register {
            get {
                return ResourceManager.GetString("Button_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обнови.
        /// </summary>
        public static string Button_Reset {
            get {
                return ResourceManager.GetString("Button_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зачувај.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прати.
        /// </summary>
        public static string Button_Send {
            get {
                return ResourceManager.GetString("Button_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ве молиме проверете го вашиот емаил.
        /// </summary>
        public static string CheckMail {
            get {
                return ResourceManager.GetString("CheckMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потврди лозинка.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нов запис.
        /// </summary>
        public static string Create_New {
            get {
                return ResourceManager.GetString("Create_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дали сте сигурни дека сакате да го избришете?.
        /// </summary>
        public static string Delete_Warning {
            get {
                return ResourceManager.GetString("Delete_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Е-маил.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внесете го вашиот емаил.
        /// </summary>
        public static string EnterMail {
            get {
                return ResourceManager.GetString("EnterMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полето {0} е задолжително.
        /// </summary>
        public static string Error_Required {
            get {
                return ResourceManager.GetString("Error_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потврди заборавена лозинка.
        /// </summary>
        public static string ForgotPassConfirm {
            get {
                return ResourceManager.GetString("ForgotPassConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заборавена лозинка?.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Јазик.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Англиски.
        /// </summary>
        public static string Language_en {
            get {
                return ResourceManager.GetString("Language_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Македонски.
        /// </summary>
        public static string Language_mk {
            get {
                return ResourceManager.GetString("Language_mk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Одјави се.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Услови за работа.
        /// </summary>
        public static string OpenJob_Conditions {
            get {
                return ResourceManager.GetString("OpenJob_Conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отворени работни места.
        /// </summary>
        public static string OpenJob_OpenJobs_id {
            get {
                return ResourceManager.GetString("OpenJob_OpenJobs_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Важи од.
        /// </summary>
        public static string OpenJob_ValidFrom {
            get {
                return ResourceManager.GetString("OpenJob_ValidFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Важи до.
        /// </summary>
        public static string OpenJob_ValidTo {
            get {
                return ResourceManager.GetString("OpenJob_ValidTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лозинка.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прашалник Одговори.
        /// </summary>
        public static string Questionare_Answers {
            get {
                return ResourceManager.GetString("Questionare_Answers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прашалник опис.
        /// </summary>
        public static string Questionare_Description {
            get {
                return ResourceManager.GetString("Questionare_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прашалник Прашања.
        /// </summary>
        public static string Questionare_Questions {
            get {
                return ResourceManager.GetString("Questionare_Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запомни.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Склад со одговори.
        /// </summary>
        public static string Repository_Answers {
            get {
                return ResourceManager.GetString("Repository_Answers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Склад со прашања.
        /// </summary>
        public static string Repository_Questions {
            get {
                return ResourceManager.GetString("Repository_Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Склад со Oдговори Опис.
        /// </summary>
        public static string RepositoryOfAnswer_Description {
            get {
                return ResourceManager.GetString("RepositoryOfAnswer_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Склад со Прашања Опис.
        /// </summary>
        public static string RepositoryOfQuestion_Description {
            get {
                return ResourceManager.GetString("RepositoryOfQuestion_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обнови лозинка.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Овозможено.
        /// </summary>
        public static string UserProfile_Enabled {
            get {
                return ResourceManager.GetString("UserProfile_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име и презиме.
        /// </summary>
        public static string UserProfile_FullName {
            get {
                return ResourceManager.GetString("UserProfile_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Корисничко име.
        /// </summary>
        public static string UserProfile_UserName {
            get {
                return ResourceManager.GetString("UserProfile_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to улога.
        /// </summary>
        public static string webpages_roles {
            get {
                return ResourceManager.GetString("webpages_roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детален опис за работното место.
        /// </summary>
        public static string WorkPosition_LongDescription {
            get {
                return ResourceManager.GetString("WorkPosition_LongDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Краток опис за работното место.
        /// </summary>
        public static string WorkPosition_ShortDescription {
            get {
                return ResourceManager.GetString("WorkPosition_ShortDescription", resourceCulture);
            }
        }
    }
}
