//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recruitment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionareAnswer
    {
        public int QuestionareAnswers_id { get; set; }
        public Nullable<int> Aplication_id { get; set; }
        public Nullable<int> RepositoryOfAnswers_id { get; set; }
        public string Answer { get; set; }
    
        public virtual Aplication Aplication { get; set; }
        public virtual RepositoryOfAnswer RepositoryOfAnswer { get; set; }
    }
}
